# Generated by Django 3.0.4 on 2020-05-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='Chinese', max_length=10),
            preserve_default=False,
        ),
    ]
